# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f16d42799d0eb73c010eb86f7f4784fb8542d3c59a3aa00526a3cfdfb3dcc39b7d5f913976de99e5cf1df53e990be22e9bc9c11d9b3f12171d3cba97b14625ad

test:
  secret_key_base: 7b8f819327bc1a4f7521de0ae9f4393786819b9be98749723233637fe2f37b3cfbf789cfc53a456ae6aee75c46ccacbd9139e616815bbaf74f4de20d195ecc88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
